### ISSUE TITLE
No message is logged upon failure of SDK `handle_events`

### ISSUE THREAD

**Issue by sorru94** [astarte-platform/astarte-message-hub#166]
The result failed of calls `handle_events` is not logged in main `run` function.

https://github.com/astarte-platform/astarte-message-hub/blob/e880fd642a0b5c60a7b5a47524fcf333eed50089/src/data/astarte_handler.rs#L193-L197

**Comment by sorru94** [comment]
This is addressed in #161.

**Comment by harlem88** [comment]
This is addressed in #168 .
