### ISSUE TITLE
Save toml-config in writable path

### ISSUE THREAD

**Issue by harlem88** [astarte-platform/astarte-message-hub#89]
When the configuration of Astarte-message-hub was provided via HTTP or GRPC-PROTOBUF APIs , the toml file generated by `MessageHubOptions` must be saved in a writable path, because the default path configured in `/etc` or the local path of message-hub may not be writable, so it should be saved in the `store_directory` provided by the `MessageHubOptions`.

**Comment by sorru94** [comment]
As per the discussion we had in private. I'll implement this as an option from the CLI.
